name: Publicar Imagen Docker

on:
  push:
    branches: [ "main", "dev" ]

jobs:
  deploy-to-azure:
    runs-on: ubuntu-latest

    env:
      SSH_KEY: ${{ github.ref_name == 'main' && secrets.SSH_KEY_PROD || secrets.SSH_KEY_DEV }}
      VM_NAME: ${{ github.ref_name == 'main' && 'vm-prod' || 'vm-dev' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install SSH client
        run: sudo apt-get install openssh-client -y

      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.9.0 # Evita exponer la clave privada en los logs
        with:
          ssh-private-key: ${{ env.SSH_KEY }}

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true

      - name: Start VM
        run: |
          az vm start --resource-group ${{ secrets.AZURE_RG }} --name ${{ env.VM_NAME }}
        shell: bash

      - name: Deploy to Azure VM (prod)
        if: github.ref_name == 'main'
        run: |
          ssh -v -o StrictHostKeyChecking=no ${{ secrets.AZURE_USER }}@${{ secrets.VM_PROD_IP }} << ENDSSH
          cd infra
          docker compose -f docker-compose.prod.yml down snippet-manager print-script-manager permissions-manager ui-service
          docker compose -f docker-compose.prod.yml pull snippet-manager print-script-manager permissions-manager ui-service
          docker compose -f docker-compose.prod.yml up -d snippet-manager print-script-manager permissions-manager ui-service
          ENDSSH

      - name: Deploy to Azure VM (dev)
        if: github.ref_name != 'main'
        run: |
          ssh -v -o StrictHostKeyChecking=no ${{ secrets.AZURE_USER }}@${{ secrets.VM_DEV_IP }} << ENDSSH
          cd infra
          docker compose -f docker-compose.dev.yml down snippet-manager print-script-manager permissions-manager ui-service
          docker compose -f docker-compose.dev.yml pull snippet-manager print-script-manager permissions-manager ui-service
          docker compose -f docker-compose.dev.yml up -d snippet-manager print-script-manager permissions-manager ui-service
          ENDSSH

      - name: Stop VM
        if: always() # Asegura que la VM se apague incluso si el despliegue falla
        run: |
          az vm deallocate --resource-group ${{ secrets.AZURE_RG }} --name ${{ env.VM_NAME }}
        shell: bash